# Generated by Django 3.2.20 on 2023-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
