# Generated by Django 3.2.20 on 2023-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
